### PR TITLE
add SpanKindClient to all spans from SQL client

### PR DESCRIPTION
**Pull request by yancl**

### CODE REVIEW

**Comment by yancl** [comment]
I saw that the reason of ci failed are:
`The command "go get -u github.com/golang/lint/..." failed and exited with 1 during`

**Comment by basvanbeek** [comment]
Thanks for your interest in ocsql @yancl, greatly appreciated.

I'm not sure if it is appropriate to set the span kind to client for any of the spans that ocsql creates. 
ocsql traces Go's database/sql abstraction and does not trace the database protocol's requests going out to the database server. The spans as such should be considered service local. If an actual database driver would get instrumented it would create the client spans and have ocsql spans as parents.

@bogdandrutu @rakyll @adriancole any insights from your end?

**Comment by yancl** [comment]
Thanks for your review @basvanbeek .

I once though that if a span was created for a remote request, it should have the client span kind. And in fact we nearly just use ocsql and don't make other explicit spans for the database driver. In this case, all spans related to DB will be local spans.  It will be fine for me that the spans are considered service local, thank you for pointing me that, greatly appreciated:)

**Comment by codefromthecrypt** [comment]
yeah a client is a client. we have always indicated it is a client even if you choose to not propagate headers (because the backend doesn't have instrumentation or for any other reason).

tagging as client is important for service graph

**Comment by basvanbeek** [comment]
Given that most, if not all, Go database/sql driver implementations are not instrumented I think it is a good idea to make ocsql's spans of type client. As @adriancole mentioned it has benefits for the service graph and is easier for consumers to reason about.

If a driver implementation pops up that does have instrumentation we can always add an option to ocsql for allowing its spans to be local again.

**Comment by yancl** [comment]
Thanks for your comments:)

**Review by basvanbeek — COMMENTED** [review]
LGTM

**Review by basvanbeek — APPROVED** [review]
Approving this... we can always circle back to adding ability to adjust the SpanKind (in case of instrumented drivers)

**Pull request merged**
