### PR TITLE
Add WithNoTraceOptions

### PR DESCRIPTION
**Pull request by ijt**
This allows explicitly disabling all tracing options.

### CODE REVIEW

**Comment by odeke-em** [comment]
@ijt thank you for the PR!

I don't think we need to add this option as it is redundant as per
https://github.com/opencensus-integrations/ocsql/blob/63b3e35325e2a92dcb0cadafa7ba9527aa3979cc/options.go#L7-L9

If you don't want any trace options, you don't need to pass in any option, so basically
```go
driverName, err = ocsql.Register("sqlite3")
```
and that should create NoOptions.

**Comment by odeke-em** [comment]
@basvanbeek perhaps we need to create some documentation about this or an `example_test.go` file with the examples that can be discovered when folks are exploring the GoDoc?

**Comment by ijt** [comment]
In that case it's redundant, but I need this to make a good API in https://github.com/google/go-cloud/issues/416. To use this stuff with `wire`, I have to be able to pass an explicit value. For example `traceOpt := withNoTraceOptions() ... wire.Value(traceOpt)`.

**Comment by odeke-em** [comment]
>In that case it's redundant, but I need this to make a good API in google/go-cloud#416. To use this stuff with wire, I have to be able to pass an explicit value. For example traceOpt := withNoTraceOptions() ... wire.Value(traceOpt).

Unfortunately I lack context as to what wire is or how it is going to relate to ocsql.

@ijt as per @basvanbeek's volunteering on the issue in https://github.com/google/go-cloud/issues/416#issue-358296170, would it be useful for you to pair with him to sort this out?

**Comment by basvanbeek** [comment]
@ijt you can also use a config struct too as I exported it in the package:

example:
```go
options := ocsql.TraceOptions{RowsClose: true}
driverName, err := ocsql.Register("driver", ocsql.WithOptions(options))
```
having the default conservative trace options with explicit config struct would then simply be:
```go
options := ocsql.TraceOptions{}
driverName, err := ocsql.Register("driver", ocsql.WithOptions(options))
```

**Comment by ijt** [comment]
@basvanbeek , that looks fine. I'll use your solution. Thanks.

**Pull request closed without merging**
